// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "order";

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  ORDER_STATUS_PENDING = 1,
  ORDER_STATUS_COMPLETED = 2,
  ORDER_STATUS_CANCELED = 3,
  ORDER_STATUS_FAILED = 4,
  /** ORDER_STATUS_EXPIRED - Its hold expired before anyone paid. */
  ORDER_STATUS_EXPIRED = 5,
  /** ORDER_STATUS_REFUND_REQUIRED - Paid, but the tickets could not be issued: the buyer is owed the money. */
  ORDER_STATUS_REFUND_REQUIRED = 6,
  ORDER_STATUS_REFUNDED = 7,
  UNRECOGNIZED = -1,
}

export interface Order {
  code: string;
  eventId: string;
  userId: string;
  userFullname: string;
  userEmail: string;
  userPhone: string;
  totalAmountCents: number;
  currency: string;
  status: OrderStatus;
  paymentMethod: string;
  items: OrderItem[];
  createdAt: string;
  updatedAt: string;
}

export interface OrderItem {
  ticketClassId: string;
  quantity: number;
  /** One ticket's price at purchase; the line costs quantity times this. */
  priceCents: number;
}

export interface CreateOrderItem {
  ticketClassId: string;
  quantity: number;
}

export interface CreateOrderRequest {
  eventId: string;
  userId: string;
  userFullname: string;
  userEmail: string;
  userPhone: string;
  paymentMethod: string;
  items: CreateOrderItem[];
  currency: string;
  checkoutToken: string;
  redirectUrl: string;
}

export interface CreateOrderResponse {
  order: Order | undefined;
  paymentUrl: string;
}

export interface PaginationInfo {
  nextCursor: string;
  pageSize: number;
  count: number;
  hasNext: boolean;
}

export interface GetManyOrdersRequest {
  cursor: string;
  pageSize: number;
  filter?: OrderFilter | undefined;
}

export interface OrderFilter {
  userId?: string | undefined;
  eventId?: string | undefined;
  status?: OrderStatus | undefined;
}

export interface GetManyOrdersResponse {
  orders: Order[];
  pagination: PaginationInfo | undefined;
}

export interface GetOrderRequest {
  code: string;
  /** The caller. Only the order's owner may read it; anyone else is told it does not exist. */
  userId: string;
}

export interface GetOrderResponse {
  order: Order | undefined;
}

export interface ListOrdersRequest {
  filter?: OrderFilter | undefined;
}

export interface ListOrdersResponse {
  orders: Order[];
}

export interface CancelOrderRequest {
  code: string;
  /** The caller. Only the order's owner may cancel it; anyone else is told it does not exist. */
  userId: string;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<CreateOrderResponse>;

  getOrder(request: GetOrderRequest): Observable<GetOrderResponse>;

  getManyOrders(request: GetManyOrdersRequest): Observable<GetManyOrdersResponse>;

  listOrders(request: ListOrdersRequest): Observable<ListOrdersResponse>;

  cancelOrder(request: CancelOrderRequest): Observable<Empty>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
  ): Promise<CreateOrderResponse> | Observable<CreateOrderResponse> | CreateOrderResponse;

  getOrder(request: GetOrderRequest): Promise<GetOrderResponse> | Observable<GetOrderResponse> | GetOrderResponse;

  getManyOrders(
    request: GetManyOrdersRequest,
  ): Promise<GetManyOrdersResponse> | Observable<GetManyOrdersResponse> | GetManyOrdersResponse;

  listOrders(
    request: ListOrdersRequest,
  ): Promise<ListOrdersResponse> | Observable<ListOrdersResponse> | ListOrdersResponse;

  cancelOrder(request: CancelOrderRequest): void;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrder", "getManyOrders", "listOrders", "cancelOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
