services:
  localstack:
    container_name: ticketbottle-order-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh
    restart: unless-stopped

volumes:
  localstack-data:
    driver: local
