{{ include "tb.appService" (dict "ctx" . "name" "order-service" "image" "ticketbottle/order-api" "port" 50054 "config" "order-config" "svcName" "order-service" "probe" "tcp") }}
---
{{ include "tb.appService" (dict "ctx" . "name" "order-consumer" "image" "ticketbottle/order-consumer" "port" 0 "config" "order-config" "probe" "none") }}
